<h1><a href="/">Home</a></h1>
<h1>Produtos do Sistema</h1>

<table>

  <tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th>Preco</th>
    <th>Restaurante Id</th>
  </tr>

  <?php foreach($data['products'] as $product): ?>
    <tr>
      <th><a href="<?=$router->pathFor('product-detail', ['id' => $product->getId()])?>"><?=$product->getName() ?></a></th>
      <th><?=$product->getDesc() ?></th>
      <th><?=$product->getPrice() ?></th>
      <th><?=$product->getRestaurantId() ?></th>
    </tr>
  <?php endforeach; ?>

</table>
