<h1><a href="/">Home</a></h1>
<h1>Restaurantes do Sistema</h1>

<table>

  <tr>
    <th>Nome</th>
    <th>Descricao</th>
  </tr>

  <?php foreach($data['restaurants'] as $restaurant): ?>
    <tr>
      <th><a href="<?=$router->pathFor('restaurant-detail', ['id' => $restaurant->getId()])?>"><?=$restaurant->getName() ?></a></th>
      <th><?=$restaurant->getDesc() ?></th>
    </tr>
  <?php endforeach; ?>

</table>
