<h1><a href="/">Home</a></h1>
<h1>Usuarios do Sistema</h1>

<table>

  <tr>
    <th>Nome</th>
    <th>Username</th>
    <th>Descricao</th>
  </tr>

  <?php foreach($data['users'] as $user): ?>
    <tr>
      <?php $username = $user->getUsername() ?>
      <th><a href="<?=$router->pathFor('user-detail', ['username' => $username])?>"><?= $user->getName() ?></a></th>
      <th><?=$user->getUsername() ?></th>
      <th><?=$user->getDesc() ?></th>
    </tr>
  <?php endforeach; ?>

</table>
